import type { AppLanguage } from '../i18n';
import { CARD_SKIN_UNLOCK_COSTS, type CardSkinKey } from '../types/cardSkin';

export interface CardSkinOption {
  key: CardSkinKey;
  title: string;
  eyebrow: string;
  description: string;
  starter: boolean;
  unlockCost: number;
  backGlyph: string;
  palette: {
    aura: string;
    frame: string;
    face: string;
    hair: string;
    fabric: string;
    accent: string;
    emblem: string;
    shadow: string;
    pip: string;
    pipShadow: string;
    paper: string;
    paperShade: string;
    edge: string;
    rank: string;
    backPrimary: string;
    backSecondary: string;
    backAccent: string;
    backPattern: string;
  };
}

const OPTIONS: CardSkinOption[] = [
  {
    key: 'classic-court',
    title: '经典宫廷',
    eyebrow: 'Starter',
    description: '标准宫廷人物牌面，读数优先，适合长局。',
    starter: true,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['classic-court'],
    backGlyph: 'C',
    palette: {
      aura: '#efe4c3',
      frame: '#d9bf72',
      face: '#f3d8bb',
      hair: '#5f2f18',
      fabric: '#94383b',
      accent: '#264f95',
      emblem: '#fff3d3',
      shadow: 'rgba(30, 19, 9, 0.24)',
      pip: '#1a2537',
      pipShadow: 'rgba(255, 255, 255, 0.34)',
      paper: '#fffdf7',
      paperShade: '#edf2fa',
      edge: 'rgba(184, 154, 82, 0.68)',
      rank: '#10203a',
      backPrimary: '#1f3563',
      backSecondary: '#123c8d',
      backAccent: '#f0d488',
      backPattern: 'rgba(255, 255, 255, 0.16)',
    },
  },
  {
    key: 'neon-royal',
    title: '霓虹皇室',
    eyebrow: 'Club Line',
    description: '蓝紫霓虹边框和冷光人物，更贴近现在的牌桌气质。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['neon-royal'],
    backGlyph: 'N',
    palette: {
      aura: '#5de8ff',
      frame: '#8a7cff',
      face: '#f1d5c7',
      hair: '#1f254e',
      fabric: '#1f5cff',
      accent: '#ef4fff',
      emblem: '#dffaff',
      shadow: 'rgba(15, 34, 89, 0.3)',
      pip: '#15254f',
      pipShadow: 'rgba(133, 248, 255, 0.18)',
      paper: '#f8fbff',
      paperShade: '#dce9ff',
      edge: 'rgba(95, 136, 255, 0.62)',
      rank: '#1c2f68',
      backPrimary: '#141e52',
      backSecondary: '#2948c9',
      backAccent: '#4ff0ff',
      backPattern: 'rgba(162, 222, 255, 0.24)',
    },
  },
  {
    key: 'velvet-opera',
    title: '绒幕歌剧',
    eyebrow: 'Premium',
    description: '红金歌剧厅风格，人物更戏剧化，适合亮眼牌面。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['velvet-opera'],
    backGlyph: 'V',
    palette: {
      aura: '#ffcca0',
      frame: '#e15a5a',
      face: '#f1d2c1',
      hair: '#31131a',
      fabric: '#7b1325',
      accent: '#f0b04e',
      emblem: '#fff0ce',
      shadow: 'rgba(59, 18, 23, 0.28)',
      pip: '#541726',
      pipShadow: 'rgba(255, 227, 189, 0.24)',
      paper: '#fffaf6',
      paperShade: '#f2e1db',
      edge: 'rgba(181, 72, 73, 0.62)',
      rank: '#661f27',
      backPrimary: '#4f1026',
      backSecondary: '#7f1936',
      backAccent: '#f0b04e',
      backPattern: 'rgba(255, 221, 192, 0.18)',
    },
  },
  {
    key: 'jade-legends',
    title: '玉辉传奇',
    eyebrow: 'Elite',
    description: '青玉与鎏金混合的东方戏服牌面，J/Q/K 和大小王层次更强。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['jade-legends'],
    backGlyph: 'J',
    palette: {
      aura: '#9ef0cb',
      frame: '#47b98b',
      face: '#f0d0b7',
      hair: '#143b32',
      fabric: '#15745f',
      accent: '#d8b14d',
      emblem: '#f2ffe5',
      shadow: 'rgba(11, 52, 41, 0.28)',
      pip: '#173f39',
      pipShadow: 'rgba(228, 255, 231, 0.24)',
      paper: '#fafffb',
      paperShade: '#e0f3ef',
      edge: 'rgba(51, 126, 110, 0.62)',
      rank: '#17463e',
      backPrimary: '#13443e',
      backSecondary: '#1a6f60',
      backAccent: '#d8b14d',
      backPattern: 'rgba(236, 255, 231, 0.18)',
    },
  },
  {
    key: 'midnight-gala',
    title: '午夜假面',
    eyebrow: 'Collector',
    description: '深蓝黑绒与银白假面纹样，牌背更像晚宴邀请函。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['midnight-gala'],
    backGlyph: 'M',
    palette: {
      aura: '#b7c8ff',
      frame: '#8da3ff',
      face: '#f2d7ca',
      hair: '#15182f',
      fabric: '#1d244c',
      accent: '#d6deff',
      emblem: '#f7f9ff',
      shadow: 'rgba(15, 22, 57, 0.32)',
      pip: '#1a2446',
      pipShadow: 'rgba(222, 232, 255, 0.24)',
      paper: '#f7f9fd',
      paperShade: '#dce3ef',
      edge: 'rgba(116, 139, 196, 0.62)',
      rank: '#1d254d',
      backPrimary: '#13182f',
      backSecondary: '#26346d',
      backAccent: '#dce4ff',
      backPattern: 'rgba(255, 255, 255, 0.18)',
    },
  },
  {
    key: 'sunset-myth',
    title: '落霞神话',
    eyebrow: 'Signature',
    description: '橘金夕照与神话纹章，数字牌和牌背都有更暖的金属感。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['sunset-myth'],
    backGlyph: 'S',
    palette: {
      aura: '#ffd3a1',
      frame: '#ff9865',
      face: '#f4d5c3',
      hair: '#4f1a1b',
      fabric: '#b03f2b',
      accent: '#f5ca64',
      emblem: '#fff5d8',
      shadow: 'rgba(85, 32, 21, 0.28)',
      pip: '#62281f',
      pipShadow: 'rgba(255, 233, 198, 0.22)',
      paper: '#fffaf3',
      paperShade: '#f6e5d6',
      edge: 'rgba(201, 112, 73, 0.66)',
      rank: '#6a2d1f',
      backPrimary: '#6c241d',
      backSecondary: '#b04b2d',
      backAccent: '#f7d37b',
      backPattern: 'rgba(255, 243, 216, 0.18)',
    },
  },
  {
    key: 'glacier-crest',
    title: '冰峰纹章',
    eyebrow: 'Mythic',
    description: '冷白冰蓝和晶体银边，牌背更像高阶锦标赛纪念牌。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['glacier-crest'],
    backGlyph: 'G',
    palette: {
      aura: '#d8f6ff',
      frame: '#74cfff',
      face: '#efd8cb',
      hair: '#173451',
      fabric: '#2c6d92',
      accent: '#ffffff',
      emblem: '#eefbff',
      shadow: 'rgba(14, 52, 84, 0.28)',
      pip: '#173a57',
      pipShadow: 'rgba(237, 252, 255, 0.28)',
      paper: '#fcfeff',
      paperShade: '#ddeff8',
      edge: 'rgba(109, 179, 222, 0.64)',
      rank: '#1b4765',
      backPrimary: '#173852',
      backSecondary: '#2a7aa4',
      backAccent: '#eefcff',
      backPattern: 'rgba(220, 247, 255, 0.22)',
    },
  },
  {
    key: 'obsidian-lattice',
    title: '曜黑密纹',
    eyebrow: 'Vault',
    description: '黑曜石底与铜青几何纹，更强调硬朗牌背和深色数字牌对比。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['obsidian-lattice'],
    backGlyph: 'O',
    palette: {
      aura: '#ddd7cb',
      frame: '#9ba8c7',
      face: '#f0d7c5',
      hair: '#111522',
      fabric: '#3a4966',
      accent: '#8ea8d9',
      emblem: '#f3f8ff',
      shadow: 'rgba(11, 18, 34, 0.34)',
      pip: '#171d2e',
      pipShadow: 'rgba(255, 255, 255, 0.18)',
      paper: '#fbfbfd',
      paperShade: '#d9dfeb',
      edge: 'rgba(104, 117, 152, 0.68)',
      rank: '#1b2339',
      backPrimary: '#111522',
      backSecondary: '#2b3752',
      backAccent: '#bccae6',
      backPattern: 'rgba(238, 246, 255, 0.14)',
    },
  },
  {
    key: 'rose-atelier',
    title: '玫瑰画室',
    eyebrow: 'Artisan',
    description: '暖白纸张、粉金描边与画室纹章，适合更柔和的人物与牌桌搭配。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['rose-atelier'],
    backGlyph: 'R',
    palette: {
      aura: '#ffe8ef',
      frame: '#f09da4',
      face: '#f4d8ca',
      hair: '#5a2437',
      fabric: '#d0687a',
      accent: '#f2c4a2',
      emblem: '#fff8fb',
      shadow: 'rgba(98, 34, 57, 0.26)',
      pip: '#6a2944',
      pipShadow: 'rgba(255, 240, 246, 0.26)',
      paper: '#fffafb',
      paperShade: '#f4e2e6',
      edge: 'rgba(222, 153, 163, 0.64)',
      rank: '#7a3046',
      backPrimary: '#65283c',
      backSecondary: '#b25169',
      backAccent: '#ffd4df',
      backPattern: 'rgba(255, 239, 244, 0.18)',
    },
  },
  {
    key: 'arcade-bloom',
    title: '霓虹花束',
    eyebrow: 'Festival',
    description: '更偏街机海报和糖彩灯箱，人物、数字牌和背面都更鲜活。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['arcade-bloom'],
    backGlyph: 'A',
    palette: {
      aura: '#ffe6a3',
      frame: '#ff8a5e',
      face: '#f3d6c7',
      hair: '#341f64',
      fabric: '#ff4f7b',
      accent: '#53d8ff',
      emblem: '#fffdf2',
      shadow: 'rgba(48, 18, 73, 0.28)',
      pip: '#3f245f',
      pipShadow: 'rgba(255, 245, 223, 0.24)',
      paper: '#fffdf8',
      paperShade: '#f4e6e0',
      edge: 'rgba(255, 136, 94, 0.68)',
      rank: '#4a255d',
      backPrimary: '#3b1f6f',
      backSecondary: '#ff4f7b',
      backAccent: '#ffd86f',
      backPattern: 'rgba(255, 248, 220, 0.18)',
    },
  },
  {
    key: 'onyx-regent',
    title: '黑曜摄政',
    eyebrow: 'Regent',
    description: '黑银宫廷风，强调冷硬对比和高识别数字牌。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['onyx-regent'],
    backGlyph: 'X',
    palette: {
      aura: '#e3e7f4',
      frame: '#8fa2c8',
      face: '#f0d7c5',
      hair: '#0f1524',
      fabric: '#34435f',
      accent: '#a7bbdc',
      emblem: '#f7fbff',
      shadow: 'rgba(15, 21, 36, 0.35)',
      pip: '#121a2f',
      pipShadow: 'rgba(250, 252, 255, 0.22)',
      paper: '#f8f9fc',
      paperShade: '#d9deea',
      edge: 'rgba(126, 138, 168, 0.68)',
      rank: '#1b2640',
      backPrimary: '#0f1524',
      backSecondary: '#2f3f60',
      backAccent: '#c8d7ee',
      backPattern: 'rgba(227, 236, 250, 0.16)',
    },
  },
  {
    key: 'mint-casino',
    title: '薄荷会所',
    eyebrow: 'Fresh',
    description: '清亮薄荷与暖金点缀，适合长时间阅读牌面。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['mint-casino'],
    backGlyph: 'T',
    palette: {
      aura: '#d8ffe7',
      frame: '#7bd8aa',
      face: '#f2dac8',
      hair: '#1d4d41',
      fabric: '#1f8f73',
      accent: '#f8d57a',
      emblem: '#f7fff9',
      shadow: 'rgba(21, 79, 64, 0.26)',
      pip: '#18463d',
      pipShadow: 'rgba(240, 255, 246, 0.28)',
      paper: '#fbfffc',
      paperShade: '#dff1e4',
      edge: 'rgba(102, 177, 138, 0.66)',
      rank: '#1b5145',
      backPrimary: '#19483f',
      backSecondary: '#2f8f76',
      backAccent: '#ffe9a8',
      backPattern: 'rgba(240, 255, 247, 0.2)',
    },
  },
  {
    key: 'scarlet-ink',
    title: '绯墨牌坊',
    eyebrow: 'Ink',
    description: '高反差红黑视觉，人物牌和数字牌边界更强。',
    starter: false,
    unlockCost: CARD_SKIN_UNLOCK_COSTS['scarlet-ink'],
    backGlyph: 'I',
    palette: {
      aura: '#ffd0d0',
      frame: '#d85c5c',
      face: '#f3d7c8',
      hair: '#2a1117',
      fabric: '#8e2436',
      accent: '#f6c46f',
      emblem: '#fff5f5',
      shadow: 'rgba(66, 18, 26, 0.32)',
      pip: '#3f1521',
      pipShadow: 'rgba(255, 237, 237, 0.24)',
      paper: '#fff9f9',
      paperShade: '#f0dfe0',
      edge: 'rgba(182, 90, 101, 0.66)',
      rank: '#571d2b',
      backPrimary: '#481521',
      backSecondary: '#8e2436',
      backAccent: '#ffd2b0',
      backPattern: 'rgba(255, 236, 236, 0.18)',
    },
  },
];

const CARD_SKIN_LOCALIZATION: Record<CardSkinKey, { title: string; eyebrow: string; description: string }> = {
  'classic-court': { title: 'Classic Court', eyebrow: 'Starter', description: 'A readable court-card baseline for long sessions.' },
  'neon-royal': { title: 'Neon Royal', eyebrow: 'Club Line', description: 'Electric blue-violet trim with a colder club-room feel.' },
  'velvet-opera': { title: 'Velvet Opera', eyebrow: 'Premium', description: 'Red-gold opera styling with stronger theatrical face cards.' },
  'jade-legends': { title: 'Jade Legends', eyebrow: 'Elite', description: 'Jade and gilt styling with richer J/Q/K and joker layering.' },
  'midnight-gala': { title: 'Midnight Gala', eyebrow: 'Collector', description: 'Dark navy velvet and silver masquerade motifs.' },
  'sunset-myth': { title: 'Sunset Myth', eyebrow: 'Signature', description: 'Warm sunset metals across number cards and card backs.' },
  'glacier-crest': { title: 'Glacier Crest', eyebrow: 'Mythic', description: 'Ice-white and crystal-blue tournament commemorative styling.' },
  'obsidian-lattice': { title: 'Obsidian Lattice', eyebrow: 'Vault', description: 'Obsidian geometry with deeper contrast on dark ranks.' },
  'rose-atelier': { title: 'Rose Atelier', eyebrow: 'Artisan', description: 'Warm paper stock with rose-gold linework and studio crests.' },
  'arcade-bloom': { title: 'Arcade Bloom', eyebrow: 'Festival', description: 'Poster-bright arcade colors across faces, pips, and backs.' },
  'onyx-regent': { title: 'Onyx Regent', eyebrow: 'Regent', description: 'Black-silver court styling with sharp rank readability.' },
  'mint-casino': { title: 'Mint Casino', eyebrow: 'Fresh', description: 'Mint green and pale gold tuned for long reading comfort.' },
  'scarlet-ink': { title: 'Scarlet Ink', eyebrow: 'Ink', description: 'High-contrast red-black styling with crisp card boundaries.' },
};

function localizeCardSkin(option: CardSkinOption, language?: AppLanguage): CardSkinOption {
  if (!language || language === 'zh-CN') {
    return option;
  }
  return {
    ...option,
    ...CARD_SKIN_LOCALIZATION[option.key],
  };
}

export function getCardSkinOptions(language?: AppLanguage): CardSkinOption[] {
  return OPTIONS.map((option) => localizeCardSkin(option, language));
}

export function getCardSkinOption(key: CardSkinKey, language?: AppLanguage): CardSkinOption {
  return localizeCardSkin(OPTIONS.find((option) => option.key === key) ?? OPTIONS[0], language);
}
